require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - db/schema.rb

# Increases "Max line length" warning from 80 to 120
LineLength:
  Max: 120

# Increases "Assignment Branch Condition size" warning from 15 to 30
Metrics/AbcSize:
  Max: 30

# Disables "Method has too many lines."
Metrics/MethodLength:
  Enabled: false

# Disables "Block has too many lines."
Metrics/BlockLength:
  Enabled: false

# Disables "Use each_with_object instead of inject."
Style/EachWithObject:
  Enabled: false

# Disables "Prefer reduce over inject."
Style/CollectionMethods:
  Enabled: false

# Disables "Missing top-level class documentation comment."
Style/Documentation:
  Enabled: false

# Disables "Use module_function instead of extend self."
Style/ModuleFunction:
  Enabled: false

# Disables "Avoid comma after the last parameter of a method call."
Style/TrailingCommaInArguments:
  Enabled: false

# Disables "Avoid comma after the last item of a hash."
Style/TrailingCommaInLiteral:
  Enabled: false

# Disables "Use nested module/class definitions instead of compact style."
Style/ClassAndModuleChildren:
  Enabled: false

# Disables "Put empty method definitions on a single line."
Style/EmptyMethod:
  Enabled: false

# Disables "Prefer annotated tokens (like %<foo>s) over unannotated tokens (like %s)."
Style/FormatStringToken:
  Enabled: false

# % literals should be delimited by ( and ).
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%w': '()'
    '%i': '()'

# Disables "Example has too many expectations."
RSpec/MultipleExpectations:
  Enabled: false

# Disables "Example has too many lines."
RSpec/ExampleLength:
  Enabled: false

# Disables "Use describe instead of feature."
Capybara/FeatureMethods:
  Enabled: false
