language: ruby
sudo: false
rvm:
  - 2.3.1
script:
  - RAILS_ENV=test bundle exec rake --trace db:create db:migrate db:test:prepare
  - bundle exec rubocop
  - bundle exec rspec spec
before_script:
  - cp config/database.yml.travis config/database.yml
bundler_args: -j4 --without development production --quiet
addons:
  postgresql: "9.6"
  chrome: stable
